server:
  port: 9002

spring:
  datasource:
    url: jdbc:h2:mem:testDB
    initialize: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true


